import { type Project } from "./constantsAndTypes";

const projects: Project[] = [
    {
        id: 1,
        title: "First Website Of My Life",
        description: ["This is the first website i have created."],
        images: ["bata_shoes.png"],
        approxStartDate: "02/08/2020",
        approxEndDate: "02/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/JjGgVvL",
        livePreview: "https://codepen.io/manish202/full/JjGgVvL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 2,
        title: "Live Analog Clock",
        description: ["Created simple live analog clock using html, css and javascript."],
        images: ["analog_clock.png"],
        approxStartDate: "09/08/2020",
        approxEndDate: "09/08/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/YzqXpGL",
        livePreview: "https://codepen.io/manish202/full/YzqXpGL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 3,
        title: "Css Button Animation",
        description: ["Created simple button animation using html and css."],
        images: ["button_animation.png"],
        approxStartDate: "10/08/2020",
        approxEndDate: "10/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/jOqPxBp",
        livePreview: "https://codepen.io/manish202/full/jOqPxBp",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 4,
        title: "Slider Without Javascript",
        description: ["Created slider using html and css only, no javascript."],
        images: ["slider.png"],
        approxStartDate: "12/08/2020",
        approxEndDate: "12/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/NWNGorE",
        livePreview: "https://codepen.io/manish202/full/NWNGorE",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 5,
        title: "Simple Animation",
        description: ["Created simple animation using html, css, javascript"],
        images: ["js_anim.png"],
        approxStartDate: "14/08/2020",
        approxEndDate: "14/08/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/poyyzwG",
        livePreview: "https://codepen.io/manish202/full/poyyzwG",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 6,
        title: "Html Css Hover Animation",
        description: ["Created simple html and css hover animation."],
        images: ["css_hover.png"],
        approxStartDate: "16/08/2020",
        approxEndDate: "16/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/wvGGXQx",
        livePreview: "https://codepen.io/manish202/full/wvGGXQx",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 7,
        title: "Basic Clothing Webpage",
        description: ["Created simple clothing webpage using html and css only."],
        images: ["cloth_website.png"],
        approxStartDate: "17/08/2020",
        approxEndDate: "17/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/VwajeMN",
        livePreview: "https://codepen.io/manish202/full/VwajeMN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 8,
        title: "Fitness Landing Page",
        description: ["Created simple fitness landing page using html, css and javascript."],
        images: ["fitness.png"],
        approxStartDate: "11/09/2020",
        approxEndDate: "11/09/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/OJNZLYN",
        livePreview: "https://codepen.io/manish202/full/OJNZLYN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 9,
        title: "Digital Studio Webpage",
        description: ["Created simple webpage using html, css and jquery."],
        images: ["digital_studio.png"],
        approxStartDate: "13/09/2020",
        approxEndDate: "13/09/2020",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://codepen.io/manish202/pen/WNwJBpN",
        livePreview: "https://codepen.io/manish202/full/WNwJBpN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 10,
        title: "Education Mp4",
        description: ["Created simple webpage using html, css, jquery."],
        images: ["ed_mp4.png"],
        approxStartDate: "21/09/2020",
        approxEndDate: "21/09/2020",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://codepen.io/manish202/pen/oNxQzVK",
        livePreview: "https://codepen.io/manish202/full/oNxQzVK",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 11,
        title: "Css Js Animation",
        description: ["Created simple animation using html, css and javascript."],
        images: ["js_anim2.png"],
        approxStartDate: "22/09/2020",
        approxEndDate: "22/09/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/ZEWmZBK",
        livePreview: "https://codepen.io/manish202/full/ZEWmZBK",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 12,
        title: "Splendorous Website",
        description: ["Created simple webpage using html, css and javascript."],
        images: ["splendorous.png"],
        approxStartDate: "15/10/2020",
        approxEndDate: "15/10/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/GRqoGvL",
        livePreview: "https://codepen.io/manish202/full/GRqoGvL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 13,
        title: "Chillaid Website",
        description: ["Created simple webpage using html, css and javascript."],
        images: ["chillaid.png"],
        approxStartDate: "29/10/2020",
        approxEndDate: "29/10/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/qBNxKLR",
        livePreview: "https://codepen.io/manish202/full/qBNxKLR",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 14,
        title: "The Modernist website",
        description: ["Created simple webpage using html, css and javascript"],
        images: ["modernist.png"],
        approxStartDate: "02/11/2020",
        approxEndDate: "02/11/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/ZEOoRPP",
        livePreview: "https://codepen.io/manish202/full/ZEOoRPP",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 15,
        title: "Klassy Restaurant",
        description: ["Created restaurant website using bootstrap, jquery and owl carousel"],
        images: ["klassy.png"],
        approxStartDate: "26/11/2020",
        approxEndDate: "26/11/2020",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript', 'jquery', 'owl-carousel'],
        sourceCode: "https://codepen.io/manish202/pen/bGwGprP",
        livePreview: "https://codepen.io/manish202/full/bGwGprP",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 16,
        title: "Fashion Hub Clothing Site",
        description: ["This is my first repo on github.","Created responsive clothing site design."],
        images: ["fashionhub.png","fashionhub2.png","fashionhub3.png","fashionhub4.png","fashionhub5.png","fashionhub6.png"],
        approxStartDate: "16/12/2020",
        approxEndDate: "18/12/2020",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript', 'jquery', 'aos.js'],
        sourceCode: "https://github.com/manish202/fashion-hub",
        livePreview: "https://manish202.github.io/fashion-hub/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 17,
        title: "Covid 19 Api",
        description: ["Simple covid 19 api project"],
        images: ["covid.png"],
        approxStartDate: "05/01/2021",
        approxEndDate: "05/01/2021",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://github.com/manish202/covid-19-api",
        livePreview: "https://manish202.github.io/covid-19-api/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 18,
        title: "Blogging",
        description: ["Simple blogging webpage"],
        images: ["sora24.png"],
        approxStartDate: "23/02/2021",
        approxEndDate: "23/02/2021",
        techAndPackages: ['html','css','bootstrap','javascript','jquery'],
        sourceCode: "https://github.com/manish202/blogging",
        livePreview: "https://manish202.github.io/blogging/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 19,
        title: "Random Color Generator",
        description: ["Created random color generator webpage using html, css and javascript."],
        images: ["color_gen.png"],
        approxStartDate: "13/03/2021",
        approxEndDate: "13/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/QWGYJRe",
        livePreview: "https://codepen.io/manish202/full/QWGYJRe",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 20,
        title: "Clock In Chart Format",
        description: ["Clock in chart format created using html, css and javascript."],
        images: ["chart-clock.png"],
        approxStartDate: "14/03/2021",
        approxEndDate: "14/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/VwmRKGV",
        livePreview: "https://codepen.io/manish202/full/VwmRKGV",
        isHighlighted: false,
        isPrivateRepo: false,
    },
];

export default projects;