import { type Project } from "./constantsAndTypes";

const projects: Project[] = [
    {
        id: 1,
        title: "First Website Of My Life",
        description: ["This is the first website i have created."],
        images: ["bata_shoes.png"],
        approxStartDate: "02/08/2020",
        approxEndDate: "02/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/JjGgVvL",
        livePreview: "https://codepen.io/manish202/full/JjGgVvL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 2,
        title: "Live Analog Clock",
        description: ["Created simple live analog clock using html, css and javascript."],
        images: ["analog_clock.png"],
        approxStartDate: "09/08/2020",
        approxEndDate: "09/08/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/YzqXpGL",
        livePreview: "https://codepen.io/manish202/full/YzqXpGL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 3,
        title: "Css Button Animation",
        description: ["Created simple button animation using html and css."],
        images: ["button_animation.png"],
        approxStartDate: "10/08/2020",
        approxEndDate: "10/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/jOqPxBp",
        livePreview: "https://codepen.io/manish202/full/jOqPxBp",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 4,
        title: "Slider Without Javascript",
        description: ["Created slider using html and css only, no javascript."],
        images: ["slider.png"],
        approxStartDate: "12/08/2020",
        approxEndDate: "12/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/NWNGorE",
        livePreview: "https://codepen.io/manish202/full/NWNGorE",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 5,
        title: "Simple Animation",
        description: ["Created simple animation using html, css, javascript"],
        images: ["js_anim.png"],
        approxStartDate: "14/08/2020",
        approxEndDate: "14/08/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/poyyzwG",
        livePreview: "https://codepen.io/manish202/full/poyyzwG",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 6,
        title: "Html Css Hover Animation",
        description: ["Created simple html and css hover animation."],
        images: ["css_hover.png"],
        approxStartDate: "16/08/2020",
        approxEndDate: "16/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/wvGGXQx",
        livePreview: "https://codepen.io/manish202/full/wvGGXQx",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 7,
        title: "Basic Clothing Webpage",
        description: ["Created simple clothing webpage using html and css only."],
        images: ["cloth_website.png"],
        approxStartDate: "17/08/2020",
        approxEndDate: "17/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/VwajeMN",
        livePreview: "https://codepen.io/manish202/full/VwajeMN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 8,
        title: "Fitness Landing Page",
        description: ["Created simple fitness landing page using html, css and javascript."],
        images: ["fitness.png"],
        approxStartDate: "11/09/2020",
        approxEndDate: "11/09/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/OJNZLYN",
        livePreview: "https://codepen.io/manish202/full/OJNZLYN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 9,
        title: "Digital Studio Webpage",
        description: ["Created simple webpage using html, css and jquery."],
        images: ["digital_studio.png"],
        approxStartDate: "13/09/2020",
        approxEndDate: "13/09/2020",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://codepen.io/manish202/pen/WNwJBpN",
        livePreview: "https://codepen.io/manish202/full/WNwJBpN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 10,
        title: "Education Mp4",
        description: ["Created simple webpage using html, css, jquery."],
        images: ["ed_mp4.png"],
        approxStartDate: "21/09/2020",
        approxEndDate: "21/09/2020",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://codepen.io/manish202/pen/oNxQzVK",
        livePreview: "https://codepen.io/manish202/full/oNxQzVK",
        isHighlighted: false,
        isPrivateRepo: false,
    },
];

export default projects;