import { type Project } from "./constantsAndTypes";

const projects: Project[] = [
    {
        id: 1,
        title: "First Website Of My Life",
        description: ["This is the first website i have created."],
        images: ["bata_shoes.png"],
        approxStartDate: "02/08/2020",
        approxEndDate: "02/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/JjGgVvL",
        livePreview: "https://codepen.io/manish202/full/JjGgVvL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 2,
        title: "Live Analog Clock",
        description: ["Created simple live analog clock using html, css and javascript."],
        images: ["analog_clock.png"],
        approxStartDate: "09/08/2020",
        approxEndDate: "09/08/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/YzqXpGL",
        livePreview: "https://codepen.io/manish202/full/YzqXpGL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 3,
        title: "Css Button Animation",
        description: ["Created simple button animation using html and css."],
        images: ["button_animation.png"],
        approxStartDate: "10/08/2020",
        approxEndDate: "10/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/jOqPxBp",
        livePreview: "https://codepen.io/manish202/full/jOqPxBp",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 4,
        title: "Slider Without Javascript",
        description: ["Created slider using html and css only, no javascript."],
        images: ["slider.png"],
        approxStartDate: "12/08/2020",
        approxEndDate: "12/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/NWNGorE",
        livePreview: "https://codepen.io/manish202/full/NWNGorE",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 5,
        title: "Simple Animation",
        description: ["Created simple animation using html, css, javascript"],
        images: ["js_anim.png"],
        approxStartDate: "14/08/2020",
        approxEndDate: "14/08/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/poyyzwG",
        livePreview: "https://codepen.io/manish202/full/poyyzwG",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 6,
        title: "Html Css Hover Animation",
        description: ["Created simple html and css hover animation."],
        images: ["css_hover.png"],
        approxStartDate: "16/08/2020",
        approxEndDate: "16/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/wvGGXQx",
        livePreview: "https://codepen.io/manish202/full/wvGGXQx",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 7,
        title: "Basic Clothing Webpage",
        description: ["Created simple clothing webpage using html and css only."],
        images: ["cloth_website.png"],
        approxStartDate: "17/08/2020",
        approxEndDate: "17/08/2020",
        techAndPackages: ['html','css'],
        sourceCode: "https://codepen.io/manish202/pen/VwajeMN",
        livePreview: "https://codepen.io/manish202/full/VwajeMN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 8,
        title: "Fitness Landing Page",
        description: ["Created simple fitness landing page using html, css and javascript."],
        images: ["fitness.png"],
        approxStartDate: "11/09/2020",
        approxEndDate: "11/09/2020",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://codepen.io/manish202/pen/OJNZLYN",
        livePreview: "https://codepen.io/manish202/full/OJNZLYN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 9,
        title: "Digital Studio Webpage",
        description: ["Created simple webpage using html, css and jquery."],
        images: ["digital_studio.png"],
        approxStartDate: "13/09/2020",
        approxEndDate: "13/09/2020",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://codepen.io/manish202/pen/WNwJBpN",
        livePreview: "https://codepen.io/manish202/full/WNwJBpN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 10,
        title: "Education Mp4",
        description: ["Created simple webpage using html, css, jquery."],
        images: ["ed_mp4.png"],
        approxStartDate: "21/09/2020",
        approxEndDate: "21/09/2020",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://codepen.io/manish202/pen/oNxQzVK",
        livePreview: "https://codepen.io/manish202/full/oNxQzVK",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 11,
        title: "Css Js Animation",
        description: ["Created simple animation using html, css and javascript."],
        images: ["js_anim2.png"],
        approxStartDate: "22/09/2020",
        approxEndDate: "22/09/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/ZEWmZBK",
        livePreview: "https://codepen.io/manish202/full/ZEWmZBK",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 12,
        title: "Splendorous Website",
        description: ["Created simple webpage using html, css and javascript."],
        images: ["splendorous.png"],
        approxStartDate: "15/10/2020",
        approxEndDate: "15/10/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/GRqoGvL",
        livePreview: "https://codepen.io/manish202/full/GRqoGvL",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 13,
        title: "Chillaid Website",
        description: ["Created simple webpage using html, css and javascript."],
        images: ["chillaid.png"],
        approxStartDate: "29/10/2020",
        approxEndDate: "29/10/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/qBNxKLR",
        livePreview: "https://codepen.io/manish202/full/qBNxKLR",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 14,
        title: "The Modernist website",
        description: ["Created simple webpage using html, css and javascript"],
        images: ["modernist.png"],
        approxStartDate: "02/11/2020",
        approxEndDate: "02/11/2020",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/ZEOoRPP",
        livePreview: "https://codepen.io/manish202/full/ZEOoRPP",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 15,
        title: "Klassy Restaurant",
        description: ["Created restaurant website using bootstrap, jquery and owl carousel"],
        images: ["klassy.png"],
        approxStartDate: "26/11/2020",
        approxEndDate: "26/11/2020",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript', 'jquery', 'owl-carousel'],
        sourceCode: "https://codepen.io/manish202/pen/bGwGprP",
        livePreview: "https://codepen.io/manish202/full/bGwGprP",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 16,
        title: "Fashion Hub Clothing Site",
        description: ["This is my first repo on github.","Created responsive clothing site design."],
        images: ["fashionhub.png","fashionhub2.png","fashionhub3.png","fashionhub4.png","fashionhub5.png","fashionhub6.png"],
        approxStartDate: "16/12/2020",
        approxEndDate: "18/12/2020",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript', 'jquery', 'aos.js'],
        sourceCode: "https://github.com/manish202/fashion-hub",
        livePreview: "https://manish202.github.io/fashion-hub/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 17,
        title: "Covid 19 Api",
        description: ["Simple covid 19 api project"],
        images: ["covid.png"],
        approxStartDate: "05/01/2021",
        approxEndDate: "05/01/2021",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://github.com/manish202/covid-19-api",
        livePreview: "https://manish202.github.io/covid-19-api/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 18,
        title: "Blogging",
        description: ["Simple blogging webpage"],
        images: ["sora24.png"],
        approxStartDate: "23/02/2021",
        approxEndDate: "23/02/2021",
        techAndPackages: ['html','css','bootstrap','javascript','jquery'],
        sourceCode: "https://github.com/manish202/blogging",
        livePreview: "https://manish202.github.io/blogging/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 19,
        title: "Random Color Generator",
        description: ["Created random color generator webpage using html, css and javascript."],
        images: ["color_gen.png"],
        approxStartDate: "13/03/2021",
        approxEndDate: "13/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/QWGYJRe",
        livePreview: "https://codepen.io/manish202/full/QWGYJRe",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 20,
        title: "Clock In Chart Format",
        description: ["Clock in chart format created using html, css and javascript."],
        images: ["chart-clock.png"],
        approxStartDate: "14/03/2021",
        approxEndDate: "14/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/VwmRKGV",
        livePreview: "https://codepen.io/manish202/full/VwmRKGV",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 21,
        title: "Quiz Api With Fetch Method",
        description: ["Quiz api with fetch method using html, css, javascript."],
        images: ["quiz_api.png"],
        approxStartDate: "15/03/2021",
        approxEndDate: "15/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/BaQbbpm",
        livePreview: "https://codepen.io/manish202/full/BaQbbpm",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 22,
        title: "Depended Apis",
        description: ["Created depended apis using html, css and javascript."],
        images: ["fun_app.png"],
        approxStartDate: "16/03/2021",
        approxEndDate: "16/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/OJbGZRo",
        livePreview: "https://codepen.io/manish202/full/OJbGZRo",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 23,
        title: "Card Hover, Dropdown Menu, Tabs, Accordion",
        description: ["Created ui components like card hover, dropdown, tabs and accordions using html, css and javascript"],
        images: ["card_hover.png"],
        approxStartDate: "22/03/2021",
        approxEndDate: "22/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/gOgYWVZ",
        livePreview: "https://codepen.io/manish202/full/gOgYWVZ",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 24,
        title: "Glassmorphism Animation",
        description: ["Created glassmorphism animation effects using html and css"],
        images: ["glassform.png"],
        approxStartDate: "22/03/2021",
        approxEndDate: "22/03/2021",
        techAndPackages: ['html', 'css'],
        sourceCode: "https://codepen.io/manish202/pen/qBRWovQ",
        livePreview: "https://codepen.io/manish202/full/qBRWovQ",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 25,
        title: "Glassmorphism Animations",
        description: ["Created glassmorphism animations with buttons, cards, clock using html, css and javascript"],
        images: ["glassmorphism.png"],
        approxStartDate: "23/03/2021",
        approxEndDate: "23/03/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/YzNPqXw",
        livePreview: "https://codepen.io/manish202/full/YzNPqXw",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 26,
        title: "Shopnow Php Ecommerce",
        description: ["This is the first php website i have created after watching youtube tutorials.", "Shopnow is php based ecommerce website design.", "Live preview is not available due to lack of web hosting, but you can download source code and run it on your localhost.", "Deployed on github on D/31/01/2023."],
        images: ["shop-now.png"],
        approxStartDate: "16/04/2021",
        approxEndDate: "18/04/2021",
        techAndPackages: ['html','css','javascript','jquery','okzoom.js','owl-carousel','php'],
        sourceCode: "https://github.com/manish202/shopnow-php-ecommerce",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 27,
        title: "Free Web Templates",
        description: ["This site provide free web templates, its just a static website."],
        images: ["freewebtemp.png"],
        approxStartDate: "09/06/2021",
        approxEndDate: "10/06/2021",
        techAndPackages: ['html','css','bootstrap','javascript','jquery','aos.js'],
        sourceCode: "https://github.com/manish202/freewebtemplates",
        livePreview: "https://manish202.github.io/freewebtemplates/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 28,
        title: "Quantum Electronic Site",
        description: ["This is just a static ecommerce site."],
        images: ["quantum.png"],
        approxStartDate: "23/06/2021",
        approxEndDate: "23/06/2021",
        techAndPackages: ['html','css','bootstrap','javascript','jquery'],
        sourceCode: "https://github.com/manish202/quantum",
        livePreview: "https://manish202.github.io/quantum/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 29,
        title: "Anime Js Animation",
        description: ["Created animation effects using html, css, javascript and animejs."],
        images: ["animjs.png"],
        approxStartDate: "28/07/2021",
        approxEndDate: "28/07/2021",
        techAndPackages: ['html', 'css', 'javascript', 'anime.js'],
        sourceCode: "https://codepen.io/manish202/pen/XWREWMm",
        livePreview: "https://codepen.io/manish202/full/XWREWMm",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 30,
        title: "Anime Js Heart Animation",
        description: ["Created heart animation using html, css, javascript and animejs."],
        images: ["animjs2.png"],
        approxStartDate: "28/07/2021",
        approxEndDate: "28/07/2021",
        techAndPackages: ['html', 'css', 'javascript', 'anime.js'],
        sourceCode: "https://codepen.io/manish202/pen/xxdWGmx",
        livePreview: "https://codepen.io/manish202/full/xxdWGmx",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 31,
        title: "Snake Game With Svg",
        description: ["Created snake game using svg and javascript"],
        images: ["snake.png"],
        approxStartDate: "03/08/2021",
        approxEndDate: "03/08/2021",
        techAndPackages: ['html', 'svg', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/GRmBWYB",
        livePreview: "https://codepen.io/manish202/full/GRmBWYB",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 32,
        title: "Scroll Animation",
        description: ["Created simple scroll based animation effects using javascript"],
        images: ["scroll_anim.png"],
        approxStartDate: "03/08/2021",
        approxEndDate: "03/08/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/oNWMwJj",
        livePreview: "https://codepen.io/manish202/full/oNWMwJj",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 33,
        title: "Bitzhub Clothing Site",
        description: ["Created static clothing website using html, css and javascript"],
        images: ["bitzhub.png"],
        approxStartDate: "12/08/2021",
        approxEndDate: "12/08/2021",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/bitzhub",
        livePreview: "https://manish202.github.io/bitzhub/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 34,
        title: "Fashion Clothing Site",
        description: ["Created fashion clothing website using jquery and swiper js"],
        images: ["fashion.png"],
        approxStartDate: "12/08/2021",
        approxEndDate: "12/08/2021",
        techAndPackages: ['html', 'css', 'javascript', 'jquery', 'swiper.js'],
        sourceCode: "https://github.com/manish202/clothing_site",
        livePreview: "https://manish202.github.io/clothing_site/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 35,
        title: "Kirana Store",
        description: ["Created kirana store website using html, css and jquery"],
        images: ["ashapuri_gro.png"],
        approxStartDate: "20/08/2021",
        approxEndDate: "20/08/2021",
        techAndPackages: ['html','css','javascript','jquery'],
        sourceCode: "https://github.com/manish202/kirana-store",
        livePreview: "https://manish202.github.io/kirana-store/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 36,
        title: "Grocery Store In Core Php With Mysql",
        description: ["Created online grocery store with admin panel using core php and mysql.", "Live preview is not available due to lack of web hosting and you can not download source code because its private repo.", "Contact me if you need source code.", "Deployed on github on D/31/01/2023.", "CMS, Dashboard", "Login, Logout, Forgot Password with google re-captcha", "Order quantity limitiation for each product", "Suggesting products based upon category", "Order validation in backend, like stock, price, quantity etc...", "User can cancel order before order dispatched.", "User can check delivery status & order history", "User get notification when place order, confirm, dispatch, deliver etc..."],
        images: ["ashapurionline.png","ashapurionline2.png","ashapurionline3.png","ashapurionline4.png","ashapurionline5.png","ashapurionline6.png","ashapurionline7.png","ashapurionline8.png","ashapurionline9.png","ashapurionline10.png"],
        approxStartDate: "15/10/2021",
        approxEndDate: "01/12/2021",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/ashapurionline/tree/main/grocery",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 37,
        title: "Dna Animation",
        description: ["Created simple dna animation using html and css."],
        images: ["dna_anim.png"],
        approxStartDate: "20/12/2021",
        approxEndDate: "20/12/2021",
        techAndPackages: ['html', 'css'],
        sourceCode: "https://codepen.io/manish202/pen/poWwQVO",
        livePreview: "https://codepen.io/manish202/full/poWwQVO",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 38,
        title: "Bootstrap Website",
        description: ["Created responsive website design using bootstrap and javascript"],
        images: ["bt_design.png"],
        approxStartDate: "20/12/2021",
        approxEndDate: "20/12/2021",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/VwMWqZp",
        livePreview: "https://codepen.io/manish202/full/VwMWqZp",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 39,
        title: "Html Css Animation",
        description: ["Created creative animation effects using html and css"],
        images: ["css_anim4.png"],
        approxStartDate: "20/12/2021",
        approxEndDate: "20/12/2021",
        techAndPackages: ['html', 'css'],
        sourceCode: "https://codepen.io/manish202/pen/BawZvwG",
        livePreview: "https://codepen.io/manish202/full/BawZvwG",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 40,
        title: "Random Animation",
        description: ["Created random animation effects using html and css"],
        images: ["rand_anim.png"],
        approxStartDate: "27/01/2022",
        approxEndDate: "27/01/2022",
        techAndPackages: ['html', 'css'],
        sourceCode: "https://codepen.io/manish202/pen/mdqyabd",
        livePreview: "https://codepen.io/manish202/full/mdqyabd",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 41,
        title: "List Of Projects",
        description: ["Created personal portfolio website."],
        images: ["all_projects.png"],
        approxStartDate: "30/01/2022",
        approxEndDate: "30/01/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/projects",
        livePreview: "https://manish202.github.io/projects/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 42,
        title: "Gold Jewellery",
        description: ["Created gold jewellery website using html, css and javascript"],
        images: ["gold.png"],
        approxStartDate: "30/01/2022",
        approxEndDate: "30/01/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/gold",
        livePreview: "https://manish202.github.io/gold/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 43,
        title: "Meme Api Site",
        description: ["Using meme api with javascript."],
        images: ["memeapi.png"],
        approxStartDate: "31/01/2022",
        approxEndDate: "31/01/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/meme-api",
        livePreview: "https://manish202.github.io/meme-api/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 44,
        title: "My First React Website",
        description: ["This is my first react website."],
        images: ["first_react.png","first_react2.png","first_react3.png","first_react4.png"],
        approxStartDate: "09/02/2022",
        approxEndDate: "09/02/2022",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript', 'react', 'react-dom', 'react-router-dom', 'react-scripts', 'gh-pages'],
        sourceCode: "https://github.com/manish202/FirstReactWebsite",
        livePreview: "https://manish202.github.io/FirstReactWebsite/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 45,
        title: "Blog Website In Core Php With Mysql",
        description: ["Created blog website with admin panel using core php and mysql.", "Live preview is not available due to lack of web hosting and you can not download source code because its private repo.", "Contact me if you need source code.", "Deployed on github on D/31/01/2023."],
        images: ["ashapuri_blog.png","ashapuri_blog2.png","ashapuri_blog3.png","ashapuri_blog4.png","ashapuri_blog5.png","ashapuri_blog6.png"],
        approxStartDate: "18/02/2022",
        approxEndDate: "22/02/2022",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/ashapurionline/tree/main/blog",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 46,
        title: "Bootstrap 5 & Git-Github",
        description: ["Learning bootstrap 5 and git-github"],
        images: ["bt5.png"],
        approxStartDate: "25/02/2022",
        approxEndDate: "25/02/2022",
        techAndPackages: ['html', 'css', 'bootstrap'],
        sourceCode: "https://github.com/manish202/bt5",
        livePreview: "https://manish202.github.io/bt5/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 47,
        title: "Cat Api In React",
        description: ["Using cat api in react app with infinite scroll"],
        images: ["catapi.png"],
        approxStartDate: "27/02/2022",
        approxEndDate: "27/02/2022",
        techAndPackages: ['html', 'css', 'bootstrap', 'javascript', 'react', 'react-dom', 'react-scripts', 'gh-pages'],
        sourceCode: "https://github.com/manish202/CatApi",
        livePreview: "https://manish202.github.io/CatApi/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 48,
        title: "Live Rotating Fan Animation",
        description: ["Created rotating fan animation using html and css"],
        images: ["fan.png"],
        approxStartDate: "23/03/2022",
        approxEndDate: "23/03/2022",
        techAndPackages: ['html', 'css'],
        sourceCode: "https://codepen.io/manish202/pen/ExoNyMN",
        livePreview: "https://codepen.io/manish202/full/ExoNyMN",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 49,
        title: "Basic Digital Clock",
        description: ["Created basic digital clock using javascript."],
        images: ["clock2.png"],
        approxStartDate: "26/03/2022",
        approxEndDate: "26/03/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/MWrpvmg",
        livePreview: "https://codepen.io/manish202/full/MWrpvmg",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 50,
        title: "Php Basic CRUD, No Javascript Or Jquery",
        description: ["Created basic php crud application without javascript or jquery.", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost.", "Deployed on github on D/26/11/2022"],
        images: ["basic_crud.png"],
        approxStartDate: "18/06/2022",
        approxEndDate: "18/06/2022",
        techAndPackages: ['html','css','bootstrap','php','mysql'],
        sourceCode: "https://github.com/manish202/php_crud/tree/main/basic_ajax_crud_no_js",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 51,
        title: "News Blog With CMS In Core Php",
        description: ["Created news blog website with CMS in core php (procedural method) and mysql database.", "There is No javascript or jquery used!", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost.", "Deployed on github on D/26/11/2022"],
        images: ["php_news_blog.png","php_news_blog22.png","php_news_blog33.png","php_news_blog44.png","php_news_blog55.png","php_news_blog66.png"],
        approxStartDate: "19/06/2022",
        approxEndDate: "22/06/2022",
        techAndPackages: ['html','css','bootstrap','php','mysql'],
        sourceCode: "https://github.com/manish202/php_news_blog",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 52,
        title: "Php Basic CRUD With Jquery",
        description: ["Created basic php crud application with jquery $.ajax method.", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost.", "Deployed on github on D/26/11/2022"],
        images: ["ajax_crud.png"],
        approxStartDate: "23/06/2022",
        approxEndDate: "23/06/2022",
        techAndPackages: ['html','css','bootstrap','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/php_crud/tree/main/jquery_ajax_crud",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 53,
        title: "Auto Number Increment",
        description: ["Created auto number increment animation using javascript"],
        images: ["auto_num_inc.png"],
        approxStartDate: "24/06/2022",
        approxEndDate: "24/06/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/QWQeGzM",
        livePreview: "https://codepen.io/manish202/full/QWQeGzM",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 54,
        title: "React Php Mysql Api CRUD",
        description: ["React crud app with php mysql api backend", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost.", "Deployed on github on D/22/11/2022"],
        images: ["react-php-mysql-api-crud.png"],
        approxStartDate: "27/06/2022",
        approxEndDate: "27/06/2022",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','react-toastify','react-scripts','php','mysql'],
        sourceCode: "https://github.com/manish202/react_php_mysql_api_crud",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 55,
        title: "React Todo List CRUD",
        description: ["Created react todo list application using bootstrap 5"],
        images: ["reactbt5.png"],
        approxStartDate: "03/07/2022",
        approxEndDate: "03/07/2022",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-scripts','gh-pages'],
        sourceCode: "https://github.com/manish202/react_crud",
        livePreview: "https://manish202.github.io/react_crud/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 56,
        title: "React Checkout Cart Page",
        description: ["Created checkout cart ui using react and mui"],
        images: ["reactcart.png"],
        approxStartDate: "07/07/2022",
        approxEndDate: "09/07/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material','react-scripts','gh-pages'],
        sourceCode: "https://github.com/manish202/react_cart",
        livePreview: "https://manish202.github.io/react_cart/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 57,
        title: "Random Movies Api In React",
        description: ["React app showing random movies using api"],
        images: ["movieapi.png"],
        approxStartDate: "12/07/2022",
        approxEndDate: "12/07/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','react-scripts','gh-pages'],
        sourceCode: "https://github.com/manish202/random-movies",
        livePreview: "https://manish202.github.io/random-movies/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 58,
        title: "React News Api",
        description: ["Using news api in react application."],
        images: ["newsapi.png"],
        approxStartDate: "13/07/2022",
        approxEndDate: "13/07/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','@emotion/react','@emotion/styled','@mui/material','react-scripts','gh-pages'],
        sourceCode: "https://github.com/manish202/react-news-api",
        livePreview: "https://manish202.github.io/react-news-api/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 59,
        title: "React Firebase Auth Project",
        description: ["Created react firebase auth project.", "Live preview is not available because, its just a simple project and its require firebase credentials so i have not hosted it anywhere.", "Deployed on github on D/31/01/2023"],
        images: ["firebase-react.png"],
        approxStartDate: "16/07/2022",
        approxEndDate: "16/07/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','react-router-dom','firebase','react-scripts'],
        sourceCode: "https://github.com/manish202/firebase-auth",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 60,
        title: "Manishpay With React",
        description: ["Created react based simple ui project"],
        images: ["manishpay.png"],
        approxStartDate: "19/07/2022",
        approxEndDate: "19/07/2022",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','react-scripts','gh-pages'],
        sourceCode: "https://github.com/manish202/manishpay",
        livePreview: "https://manish202.github.io/manishpay/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 61,
        title: "Mern Auth Project",
        description: ["Created mern stack authentication project using jwt and bcryptjs", "Live preview is not available because, its just a simple project so i have not hosted it anywhere.", "Deployed on github on D/31/01/2023"],
        images: ["mern-auth.png"],
        approxStartDate: "24/07/2022",
        approxEndDate: "24/07/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','react-router-dom','react-cookie','bcryptjs','react-scripts','node','express','mongodb','mongoose','jsonwebtoken','cors','dotenv'],
        sourceCode: "https://github.com/manish202/mern-auth",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 62,
        title: "Blinkit Clone MERN (No CMS)",
        description: ["Note: This project is hosted on render.com free tier plan, so its instance can get sleep due to inactivity. Wait for a 1-2 minute so instance can get ready.", "Created blinkit clone using MERN stack with location access.", "Deployed on github on D/06/12/2022", "Access user location using coordinates & external geocoding API service.", "Search bar: category, subcategory, brand suggestions and product search.", "Products card in ui and products card in sidebar cart are synced.", "Created sliders using swiper.js", "Fetching all products and slides data using API.", "APIS are created using node, express, mongodb, mongoose."],
        images: ["blinkit.png","blinkit2.png","blinkit3.png","blinkit4.png","blinkit5.png","blinkit6.png","blinkit7.png","blinkit8.png"],
        approxStartDate: "30/07/2022",
        approxEndDate: "15/08/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','react-router-dom','react-toastify','swiper.js','react-scripts','node','express','mongodb','mongoose','dotenv'],
        sourceCode: "https://github.com/manish202/blinkit_clone",
        livePreview: "https://blinkit-clone-mwfj.onrender.com/",
        isHighlighted: true,
        isPrivateRepo: false,
    },
    {
        id: 63,
        title: "Pure Javascript Todo App",
        description: ["Created todo application using pure javascript and localstorage"],
        images: ["purejstodo.png"],
        approxStartDate: "28/08/2022",
        approxEndDate: "28/08/2022",
        techAndPackages: ['html','css','bootstrap','javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/todo",
        livePreview: "https://manish202.github.io/javascript-projects/todo/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 64,
        title: "Javascript Timers & Clock",
        description: ["Created javascript timers and clock project","Created clock, alarm, countdown, stopwatch"],
        images: ["jsclock.png"],
        approxStartDate: "29/08/2022",
        approxEndDate: "29/08/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/timer",
        livePreview: "https://manish202.github.io/javascript-projects/timer/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 65,
        title: "Javascript Budget App",
        description: ["Created budget app using javascript and localstorage"],
        images: ["budgetapp.png"],
        approxStartDate: "30/08/2022",
        approxEndDate: "30/08/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/budgetapp",
        livePreview: "https://manish202.github.io/javascript-projects/budgetapp/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 66,
        title: "Javascript Calculator",
        description: ["Created basic calculator using javascript"],
        images: ["calculator.png"],
        approxStartDate: "30/08/2022",
        approxEndDate: "30/08/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/calculator",
        livePreview: "https://manish202.github.io/javascript-projects/calculator/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 67,
        title: "Javascript Carousel",
        description: ["Created image carousel using javascript."],
        images: ["carousel.png"],
        approxStartDate: "30/08/2022",
        approxEndDate: "30/08/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/carousel",
        livePreview: "https://manish202.github.io/javascript-projects/carousel/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 68,
        title: "Random Password Generator",
        description: ["Created random password generator using javascript."],
        images: ["passgen.png"],
        approxStartDate: "03/09/2022",
        approxEndDate: "03/09/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/pass_generator",
        livePreview: "https://manish202.github.io/javascript-projects/pass_generator/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 69,
        title: "Javascript Random Color Generator",
        description: ["Created random color generator using javascript"],
        images: ["colorgen.png"],
        approxStartDate: "05/09/2022",
        approxEndDate: "05/09/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/color_generator",
        livePreview: "https://manish202.github.io/javascript-projects/color_generator/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 70,
        title: "Clock In Chart Format",
        description: ["Created clock in chart format using javascript"],
        images: ["chartclock.png"],
        approxStartDate: "06/09/2022",
        approxEndDate: "06/09/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/javascript-projects/tree/master/chart_clock",
        livePreview: "https://manish202.github.io/javascript-projects/chart_clock/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 71,
        title: "Responsive Dropdown Menu",
        description: ["Created responsive multiple dropdown navigation menu using javascript"],
        images: ["dropdown-nav.png"],
        approxStartDate: "11/10/2022",
        approxEndDate: "11/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/qBYLdaO",
        livePreview: "https://codepen.io/manish202/full/qBYLdaO",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 72,
        title: "Multiplication Table Using Javascript",
        description: ["Created multiplication table dynamically using javascript"],
        images: ["mult_table.png"],
        approxStartDate: "19/10/2022",
        approxEndDate: "19/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/wvjbEGx",
        livePreview: "https://codepen.io/manish202/full/wvjbEGx",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 73,
        title: "Data Converter Like Gb-Kb",
        description: ["Created data size converter using javascript"],
        images: ["data_conv.png"],
        approxStartDate: "20/10/2022",
        approxEndDate: "20/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/poVXeWm",
        livePreview: "https://codepen.io/manish202/full/poVXeWm",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 74,
        title: "Age Calculator Using Javascript",
        description: ["Created age calculator application using javascript"],
        images: ["age_calc.png"],
        approxStartDate: "20/10/2022",
        approxEndDate: "20/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/vYjqWxE",
        livePreview: "https://codepen.io/manish202/full/vYjqWxE",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 75,
        title: "Time Converter Using Javascript",
        description: ["Created time unit converter using javascript"],
        images: ["time_conv.png"],
        approxStartDate: "20/10/2022",
        approxEndDate: "20/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/vYjqpVp",
        livePreview: "https://codepen.io/manish202/full/vYjqpVp",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 76,
        title: "Tick Tack Toe Game Logic",
        description: ["Tic tac toe game logic implemented using javascript"],
        images: ["ticktacktoe.png"],
        approxStartDate: "21/10/2022",
        approxEndDate: "21/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/JjvgGRd",
        livePreview: "https://codepen.io/manish202/full/JjvgGRd",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 77,
        title: "Random Dog Images Api",
        description: ["Random dog images fetched using public api"],
        images: ["dog_img_api.png"],
        approxStartDate: "28/10/2022",
        approxEndDate: "28/10/2022",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://codepen.io/manish202/pen/mdKJBmr",
        livePreview: "https://codepen.io/manish202/full/mdKJBmr",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 78,
        title: "Json File CRUD With React & Node",
        description: ["Doing crud operation with json file using reactjs & nodejs.", "Live preview is not available due to lack of hosting, but you can download source code and run it on your localhost."],
        images: ["react-node-fs-crud.png"],
        approxStartDate: "11/11/2022",
        approxEndDate: "11/11/2022",
        techAndPackages: ['html','css','javascript','react','react-dom','react-toastify','react-scripts','node','cors'],
        sourceCode: "https://github.com/manish202/react_node_json_crud",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 79,
        title: "Github Users Api",
        description: ["Fetching github users api data in react application."],
        images: ["github-users-api.png"],
        approxStartDate: "08/12/2022",
        approxEndDate: "13/12/2022",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','react-scripts','@mui/icons-material'],
        sourceCode: "https://github.com/manish202/github_users_api",
        livePreview: "https://github-users-api.onrender.com",
        isHighlighted: true,
        isPrivateRepo: false,
    },
    {
        id: 80,
        title: "Wordpress Website",
        description: ["I have tried to create wordpress based hair salon business website.", "I was just trying to get some freelance work. This is my 1st attempt/experiment to get some freelance work.", "I was just randomly targeting any business and trying to create there website without there requirement. If they will like my work then they will pay me for that, otherwise this project will become part of my portfolio, and my portfolio can help me to get some freelance work.", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost.", "Deployed on github on D/31/01/2023"],
        images: ["laima-unisex.png"],
        approxStartDate: "30/12/2022",
        approxEndDate: "31/12/2022",
        techAndPackages: ['html','css','javascript','php','mysql','wordpress'],
        sourceCode: "https://github.com/manish202/laima_unisex_salon",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 81,
        title: "Personal Portfolio Website",
        description: ["Created personal portfolio website using html, css and javascript.", "I have created this personal portfolio website for freelancing purpose."],
        images: ["my-portfolio.png"],
        approxStartDate: "04/01/2023",
        approxEndDate: "05/01/2023",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/portfolio",
        livePreview: "https://manish202.github.io/portfolio/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 82,
        title: "Onwardpass V1 (Paytm Payment Gateway)",
        description: ["This is my 1st freelancing project. I got this work from facebook.", "I was just trying to get some freelance work. This is my 2nd attempt/experiment to get some freelance work.", "I have converted figma file design into html and css.", "I have used html, css and jquery in client side and core php and mysql database in server side.", "I have not used any frontend or backend framework because i have not learned that at that time.", "I have created booking page where user can book only flight or flight + hotel or only hotel as per user need.", "I have used third-party APIs to validate whether a flight is available for a particular route or not.", "If the flight is available, the user is redirected to the payment page where they can see their details and use a coupon code.", "I have integrated paytm payment gateway so users can pay online.", "Admin can view bookings and payment details in the admin panel.", "OnwardPass™ is a service that provides valid flight reservations/dummy ticket. These reservations come with a live PNR (Passenger Name Record) code that can be verified on major airline websites.", "OnwardPass™ provide Proof of Travel that can serve various purposes, such as supporting a visa application, providing information at border crossings, serving as proof of return ticket, and being used as part of passport applications.","A \"Dummy Ticket\" is a term used to describe a confirmed flight reservation that is pending payment, indicating that the flight is on hold.", "Deployed on github on D/10/11/2023"],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "08/01/2023",
        approxEndDate: "15/02/2023",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v1",
        livePreview: "https://onwardpass.com",
        isHighlighted: true,
        isPrivateRepo: true,
    },
    {
        id: 83,
        title: "News Blog 2 With CMS In Core Php",
        description: ["Created news blog website 2nd time with CMS in core php (procedural method) and mysql database.", "There is No javascript or jquery used!", "Developed 2nd time for revision.", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost.", "Deployed on github on D/11/06/2023"],
        images: ["php_news_blog2.png"],
        approxStartDate: "22/05/2023",
        approxEndDate: "25/05/2023",
        techAndPackages: ['html','css','php','mysql'],
        sourceCode: "https://github.com/manish202/php_news_blog2",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 84,
        title: "Restaurant Website In React",
        description: ["I have tried to create restaurant website using reactjs.", "I was just trying to get some freelance work. This is my 3rd attempt/experiment to get some freelance work.", "I was just randomly targeting any business and trying to create there website without there requirement. If they will like my work then they will pay me for that, otherwise this project will become part of my portfolio, and my portfolio can help me to get some freelance work."],
        images: ["naans-curries.png"],
        approxStartDate: "28/05/2023",
        approxEndDate: "11/06/2023",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','react-scripts','serve','php'],
        sourceCode: "https://github.com/manish202/naans-curries",
        livePreview: "https://naans-and-curries.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 85,
        title: "Hair Salon Website In Nextjs",
        description: ["I have tried to create indulge hair salon website using nextjs.", "I was just trying to get some freelance work. This is my 4th attempt/experiment to get some freelance work.", "I was just randomly targeting any business and trying to create there website without there requirement. If they will like my work then they will pay me for that, otherwise this project will become part of my portfolio, and my portfolio can help me to get some freelance work."],
        images: ["indulge.png"],
        approxStartDate: "17/06/2023",
        approxEndDate: "17/06/2023",
        techAndPackages: ['html','css','javascript','react','react-dom','next','serve'],
        sourceCode: "https://github.com/manish202/indulgestyle",
        livePreview: "https://indulgestyle.onrender.com",
        isHighlighted: true,
        isPrivateRepo: false,
    },
    {
        id: 86,
        title: "Startheria V1 (Html Version)",
        description: ["I have customized existing startheria web pages in html.", "I was just trying to get some freelance work. This is my 5th attempt/experiment to get some freelance work.", "I have seen this job posting on upwork freelancing platform. I have applied on this job after creating sample website in html as per client requirement, but unfortunately i didnt got any response, so what i did is i have created short screen recording video of this website and i have contacted client through linkedin than after a few days i got response."],
        images: ["startheria.png"],
        approxStartDate: "28/06/2023",
        approxEndDate: "06/07/2023",
        techAndPackages: ['html','css','javascript'],
        sourceCode: "https://github.com/manish202/startheria_v1",
        livePreview: "https://www.startheria.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 87,
        title: "Personal Portfolio Website",
        description: ["Created personal portfolio website.", "I have created this personal portfolio website for freelancing purpose."],
        images: ["personal_portfolio.png"],
        approxStartDate: "13/07/2023",
        approxEndDate: "13/07/2023",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/my-portfolio",
        livePreview: "https://manish202.github.io/my-portfolio/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 88,
        title: "PWA, Indexeddb, Debouncing, Throttling",
        description: ["Learing pwa, indexeddb, debouncing, and throttling concepts.", "Deployed on github on D/20/10/2023"],
        images: ["pwa_indexdb_debouncing_throttling.png"],
        approxStartDate: "30/07/2023",
        approxEndDate: "30/07/2023",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/pwa_indexedDB_debouncing_throttling",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 89,
        title: "Hello World Chrome Extension",
        description: ["Learning to create basic chrome extension using javascript.", "Deployed on github on D/21/10/2023"],
        images: ["chrome_extension.png"],
        approxStartDate: "01/08/2023",
        approxEndDate: "01/08/2023",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/hello_world_chrome_extension",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 90,
        title: "React Mui Todo App",
        description: ["Created todo application using react and material ui.", "Deployed on github on D/25/10/2023"],
        images: ["react_mui_todo_app.png"],
        approxStartDate: "12/08/2023",
        approxEndDate: "12/08/2023",
        techAndPackages: ['html','css','javascript','react','react-dom','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material','vite'],
        sourceCode: "https://github.com/manish202/react-todo-with-mui",
        livePreview: "https://react-todo-app-o1je.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 91,
        title: "React Mui Weather App",
        description: ["Created weather application using react and material ui.", "Deployed on github on D/25/10/2023"],
        images: ["weather-app.png"],
        approxStartDate: "13/08/2023",
        approxEndDate: "13/08/2023",
        techAndPackages: ['html','css','javascript','react','react-dom','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material','vite'],
        sourceCode: "https://github.com/manish202/weather-app-mui",
        livePreview: "https://react-weather-app-mui.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 92,
        title: "Startheria V2 (Php Version)",
        description: ["I have converted startheria v1 (html version) into php version as per client requirement.", "I was just trying to get some freelance work. This is my 5th attempt/experiment to get some freelance work.", "I have seen this job posting on upwork freelancing platform. I have applied on this job after creating sample website in html as per client requirement, but unfortunately i didnt got any response, so what i did is i have created short screen recording video of this website and i have contacted client through linkedin than after a few days i got response. We got connected on upwork and i have accepted job proposal."],
        images: ["startheria.png"],
        approxStartDate: "04/09/2023",
        approxEndDate: "05/09/2023",
        techAndPackages: ['html','css','javascript','php'],
        sourceCode: "https://github.com/manish202/startheria_v2",
        livePreview: "https://www.startheria.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 93,
        title: "Onwardpass V2 (Phonepe Payment Gateway)",
        description: ["Due to some reasons we have to change our payment gateway so i have created onwardpass v2 (phonepe payment gateway) based upon onwardpass v1 (paytm payment gateway).", "I have integrated phonepe payment gateway so users can pay online.", "I have created new b2b.php page for travel agents.", "I have added new coupon code feature for travel agents and admin can manage coupon code in admin panel.", "I have added new hotel voucher feature so user can choose it along with flight and admin can see that in admin panel along with flight booking details.", "I have added 2 new options in booking page, receive ticket (receive now, receive later) and validity ticket (48 hours, 7 days)", "And i have did so many other improvements in code."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "14/09/2023",
        approxEndDate: "28/09/2023",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v2",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 94,
        title: "React Music Player App",
        description: ["Created music player application using react and material ui.", "Deployed on github on D/14/11/2023"],
        images: ["reactjs-music-player.png"],
        approxStartDate: "29/09/2023",
        approxEndDate: "29/09/2023",
        techAndPackages: ['html','css','javascript','react','react-dom','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material','vite'],
        sourceCode: "https://github.com/manish202/reactjs-music-player",
        livePreview: "https://reactjs-music-player.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 95,
        title: "Startheria V3 (Php Version)",
        description: ["This is my 2nd freelancing project. I got this work from upwork.", "I was just trying to get some freelance work. This is my 5th attempt/experiment to get some freelance work.","I have customized existing startheria's multiple characters web pages in php.", "I have seen this job posting on upwork freelancing platform. I have applied on this job after creating sample website in html as per client requirement, but unfortunately i didnt got any response, so what i did is i have created short screen recording video of this website and i have contacted client through linkedin than after a few days i got response. We got connected on upwork and i have accepted job proposal."],
        images: ["startheria.png"],
        approxStartDate: "03/10/2023",
        approxEndDate: "05/10/2023",
        techAndPackages: ['html', 'css', 'javascript', 'php'],
        sourceCode: "https://github.com/manish202/startheria_v3",
        livePreview: "https://www.startheria.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 96,
        title: "Onwardpass V3 (Paytm Payment Gateway)",
        description: ["I have created improved version of onwardpass v1 (paytm payment gateway)."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "13/10/2023",
        approxEndDate: "15/10/2023",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v3",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 97,
        title: "Onwardpass V4 (Phonepe Payment Gateway)",
        description: ["I have created improved version of onwardpass v2 (phonepe payment gateway)."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "16/10/2023",
        approxEndDate: "18/10/2023",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v4",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 98,
        title: "React Video Player App",
        description: ["Created video player application using react and material ui."],
        images: ["reactjs-video-player.png"],
        approxStartDate: "18/10/2023",
        approxEndDate: "18/10/2023",
        techAndPackages: ['html','css','javascript','react','react-dom','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material','vite'],
        sourceCode: "https://github.com/manish202/reactjs-video-player",
        livePreview: "https://reactjs-video-player.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 99,
        title: "Onwardproof (Stripe Payment Gateway)",
        description: ["Created onwardproof (stripe payment gateway) because client is planning to target international clients.", "I have converted onwardpass in onwardproof with stripe payment gateway."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "19/10/2023",
        approxEndDate: "23/10/2023",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardproof",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 100,
        title: "News Blog With CMS In Laravel",
        description: ["This is my first laravel project.", "Created news blog website with custom cms and session based authentication.", "Live preview is not available due to lack of web hosting but you can download source code and run it on your localhost."],
        images: ["laravel_news_blog.png"],
        approxStartDate: "25/10/2023",
        approxEndDate: "27/10/2023",
        techAndPackages: ['html','css','bootstrap','php','mysql','laravel'],
        sourceCode: "https://github.com/manish202/laravel_news_blog",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 101,
        title: "Blinkit Ecom MERN (With CMS)",
        description: ["Note: This project is hosted on render.com free tier plan, so its instance can get sleep due to inactivity. Wait for a 1-2 minute so instance can get ready.", "Created blinkit clone 2nd time using mern stack with custom cms and MVC pattern.", "First version does not include cms but this version have custom cms.", "First version is created using custom css but this version is using bootstrap.", "Access user location using coordinates & external geocoding api service.", "Users can search products.", "Users can register, login, logout.", "Products card in ui and products card in sidebar cart are synced.", "All APIS are created using node, express, mongodb, mongoose.", "User can place order and see order history and status.", "Admin can perform CRUD operation in admin panel with orders, products, categories, sub categories, brands and users.", "You can not download source code because its private repo.", "Contact me if you need source code."],
        images: ["blinkit-ecom.png","blinkit-ecom2.png","blinkit-ecom3.png","blinkit-ecom4.png","blinkit-ecom5.png","blinkit-ecom6.png","blinkit-ecom7.png","blinkit-ecom8.png","blinkit-ecom9.png","blinkit-ecom10.png","blinkit-ecom11.png","blinkit-ecom12.png","blinkit-ecom13.png","blinkit-ecom14.png",],
        approxStartDate: "01/11/2023",
        approxEndDate: "16/11/2023",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','react-toastify','react-redux','@reduxjs/toolkit','vite','node','express','mongodb','mongoose','bcryptjs','body-parser','cors','dotenv','jsonwebtoken','multer'],
        sourceCode: "https://github.com/manish202/blinkit_ecom",
        livePreview: "https://blinkit-ecom-88bh.onrender.com",
        isHighlighted: true,
        isPrivateRepo: true,
    },
    {
        id: 102,
        title: "Restaurant Site With Nextjs",
        description: ["I have tried to convert ready made restaurant website html template in nextjs"],
        images: ["nextjs-restaurant.png"],
        approxStartDate: "19/11/2023",
        approxEndDate: "19/11/2023",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','next'],
        sourceCode: "https://github.com/manish202/nextjs-restaurant",
        livePreview: "https://nextjs-restaurant.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 103,
        title: "Onwardpass V5 (Razorpay Payment Gateway)",
        description: ["Website is working very smooth with existing payment gateway, but After a few months client is facing some issues with phonepe and paytm payment gateway, so we have decided to go with razorpay payment gateway.", "I have integrated razorpay payment gateway so users can pay online.", "I have added new feature where admin can convert hotel form into pdf file."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "12/12/2023",
        approxEndDate: "28/12/2023",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v5",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 104,
        title: "My Todo App",
        description: ["I was just trying to create basic todo app in react without using CRA or VITE by using babel and webpack manual configuration."],
        images: ["my-todo-app.png"],
        approxStartDate: "29/12/2023",
        approxEndDate: "29/12/2023",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','@reduxjs/toolkit','react-redux','@babel/core','@babel/preset-env','@babel/preset-react','babel-loader','css-loader','html-webpack-plugin','mini-css-extract-plugin','style-loader','webpack','webpack-cli','webpack-dev-server'],
        sourceCode: "https://github.com/manish202/my-todo-app",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 105,
        title: "Startheria V4 (Php Version)",
        description: ["This is my 2nd freelancing project. I got this work from upwork.", "I was just trying to get some freelance work. This is my 5th attempt/experiment to get some freelance work.", "I have created slider of startheria's multiple characters animation for home page.", "I have seen this job posting on upwork freelancing platform. I have applied on this job after creating sample website in html as per client requirement, but unfortunately i didnt got any response, so what i did is i have created short screen recording video of this website and i have contacted client through linkedin than after a few days i got response. We got connected on upwork and i have accepted job proposal."],
        images: ["startheria.png"],
        approxStartDate: "03/01/2024",
        approxEndDate: "10/01/2024",
        techAndPackages: ['html', 'css', 'javascript', 'php'],
        sourceCode: "https://github.com/manish202/startheria_v4",
        livePreview: "https://www.startheria.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 106,
        title: "Web Dev Revision",
        description: ["Doing revision of web development from 24/03/2024 to 14/04/2024"],
        images: ["web_dev_revision.png"],
        approxStartDate: "24/03/2024",
        approxEndDate: "14/04/2024",
        techAndPackages: ['html','css','sass','bootstrap','javascript','jquery','typescript','git-github','react','react-dom','php','mysql','node','express','mongodb','mongoose'],
        sourceCode: "https://github.com/manish202/web_dev_revision",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 107,
        title: "React Multiple Projects",
        description: ["Created multiple projects in reactjs, including todo app, accordion, github users and shopping cart."],
        images: ["todoapp_accordion_githubusers_shoppingcart.png"],
        approxStartDate: "15/04/2024",
        approxEndDate: "15/04/2024",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom'],
        sourceCode: "https://github.com/manish202/react_projects",
        livePreview: "https://manish202.github.io/react_projects/",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 108,
        title: "Mern Auth Project 2",
        description: ["Note: This project is hosted on render.com free tier plan, so its instance can get sleep due to inactivity. Wait for a 1-2 minute so instance can get ready.", "Created mern stack authentication project using jwt and bcryptjs 2nd time for revision."],
        images: ["mern_project.png"],
        approxStartDate: "17/04/2024",
        approxEndDate: "17/04/2024",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','react-scripts','node','express','mongodb','mongoose','bcryptjs','cookie-parser','dotenv','jsonwebtoken'],
        sourceCode: "https://github.com/manish202/mern_project",
        livePreview: "https://mern-project-9xcw.onrender.com",
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 109,
        title: "Styled Components In React",
        description: ["Learning, Practicing styled components in react."],
        images: ["styled-compo.png"],
        approxStartDate: "21/04/2024",
        approxEndDate: "21/04/2024",
        techAndPackages: ['html','css','javascript','react','react-dom','react-router-dom','styled-components','vite'],
        sourceCode: "https://github.com/manish202/styled-compo-practice",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 110,
        title: "React Static E-commerce",
        description: ["Created static ecommerce site using react and styled components."],
        images: ["react-static-ecom.png"],
        approxStartDate: "22/04/2024",
        approxEndDate: "27/04/2024",
        techAndPackages: ['html','css','javascript','react','react-dom','@auth0/auth0-react','react-icons','react-router-dom','styled-components','vite'],
        sourceCode: "https://github.com/manish202/react-static-ecom",
        livePreview: "https://react-static-ecom.onrender.com",
        isHighlighted: true,
        isPrivateRepo: false,
    },
    {
        id: 111,
        title: "Redux Toolkit Practice",
        description: ["Practicing redux and redux-toolkit."],
        images: ["redux_toolkit.png"],
        approxStartDate: "28/04/2024",
        approxEndDate: "28/04/2024",
        techAndPackages: ['html','css','javascript','react','react-dom','redux','react-redux','@reduxjs/toolkit','vite'],
        sourceCode: "https://github.com/manish202/redux_toolkit_practice",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 112,
        title: "Nextjs Pages Router Tutorial",
        description: ["Nextjs pages router tutorial completed from youtube."],
        images: ["nextjs_tutorial.png"],
        approxStartDate: "29/04/2024",
        approxEndDate: "29/04/2024",
        techAndPackages: ['html','css','javascript','react','react-dom','next'],
        sourceCode: "https://github.com/manish202/nextjs_tutorial",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 113,
        title: "Nextjs App Router Tutorial",
        description: ["Nextjs app router tutorial completed from youtube."],
        images: ["nextjs_tutorial2.png"],
        approxStartDate: "30/04/2024",
        approxEndDate: "30/04/2024",
        techAndPackages: ['html','css','javascript','react','react-dom','next','react-icons'],
        sourceCode: "https://github.com/manish202/nextjs_tutorial_2",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: false,
    },
    {
        id: 114,
        title: "Graphql Exploration Project",
        description: ["First time exploring graphql with react and mongodb.", "You can not download source code because its private repo.", "Contact me if you need source code."],
        images: ["first_graphql_project.png"],
        approxStartDate: "08/05/2024",
        approxEndDate: "09/05/2024",
        techAndPackages: ['html','css','bootstrap','javascript','react','react-dom','react-router-dom','graphql','@apollo/client','vite','node','mongodb','mongoose','apollo-server','apollo-server-core','bcryptjs','jsonwebtoken'],
        sourceCode: "https://github.com/manish202/first_fraphql_project",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 115,
        title: "Personal Portfolio Website",
        description: ["Created personal portfolio website."],
        images: ["best_portfolio.png"],
        approxStartDate: "23/05/2024",
        approxEndDate: "23/05/2024",
        techAndPackages: ['html', 'css', 'javascript'],
        sourceCode: "https://github.com/manish202/best_portfolio",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 116,
        title: "Onwardpass V6 (Phonepe Payment Gateway)",
        description: ["Website is working very smooth with existing razorpay payment gateway, but After a few months client wants to switch back to the phonepe payment gateway due to some reasons, and also want some changes with existing features, so i have created new version with phonepe payment gateway and other improvements."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "02/07/2024",
        approxEndDate: "05/07/2024",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v6",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 117,
        title: "Laravel Tutorial",
        description: ["Laravel tutorial completed from yahoo baba youtube channel."],
        images: ["laravel_tutorial_from_yt.png"],
        approxStartDate: "05/07/2024",
        approxEndDate: "16/07/2024",
        techAndPackages: ['html','css','javascript','php','mysql','laravel'],
        sourceCode: "https://github.com/manish202/laravel_tutorial",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 118,
        title: "Onwardpass V7 (Phonepe Payment Gateway)",
        description: ["This is the improved stable version of v6 for production use.", "I have used phonepe php sdk."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "24/09/2024",
        approxEndDate: "30/09/2024",
        techAndPackages: ['html','css','javascript','jquery','php','mysql'],
        sourceCode: "https://github.com/manish202/onwardpass_v7",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 119,
        title: "Onwardpass V8 (Phonepe Payment Gateway)",
        description: ["Onwardpass v1 to v7 all versions are based on core php and mysql database, so i was trying to convert onwardpass v7 into laravel framework.", "This version is not fully completed and not ready for production use."],
        images: ["onwardpass_v1.png","onwardpass_v1_2.png","onwardpass_v1_3.png","onwardpass_v1_4.png","onwardpass_v1_5.png","onwardpass_v1_6.png","onwardpass_v1_7.png","onwardpass_v1_8.png","onwardpass_v1_9.png","onwardpass_v1_10.png","onwardpass_v1_11.png"],
        approxStartDate: "15/10/2024",
        approxEndDate: "16/10/2024",
        techAndPackages: ['html','css','javascript','jquery','php','mysql','laravel'],
        sourceCode: "https://github.com/manish202/onwardpass_v8",
        livePreview: "https://onwardpass.com",
        isHighlighted: false,
        isPrivateRepo: true,
    },
    {
        id: 120,
        title: "Onwardpass Travelport V1",
        description: ["Started working on travelport api for onwardpass client.", "Travelport is a global technology company that runs a Global Distribution System (GDS), connecting travel suppliers like airlines and hotels with travel agencies and buyers.", "Travelport links thousands of travel agencies with hundreds of airlines, hotel chains, and car rental companies worldwide.", "Travelport allows travel sellers to search, compare, book, and pay for travel services in real time through a single system.", "Travelport owns and operates legacy booking systems including Galileo, Apollo, and Worldspan.", "Onwardpass client wants me to create user interface and integrate this Travelport Legacy SOAP/XML based Universal API (uAPI) for airline and hotel booking.", "This project was very challenging for me because i have never worked with SOAP/XML based APIS. But i was learning, exploring and trying to implement it.", "I have used node express in backend for creating APIS which is interacticing with travelport SOAP/XML based APIS.", "I have used hbs template engine for serving user interface/web pages instead of using any other library/framework like react, angular, vue etc..", "Here your can visit (https://demo.travelportuniversalapi.com/Home) and understand what kind of flow i was trying to implement.", "I have created user interface where admin fill form and submit it, behind the scene what i need to do is i need to convert that form data in XML format and send it as a payload request to the travel api end point and i need to parse response XML data in JSON so i can send it back to the user interface.", "I was struggling with travelport api because there are so many endpoints and each end point has so many parameters at deeper level and parsing XML into JSON is difficult part, for each request they are sending very huge XML response.", "But finally i have completed this project from my side."],
        images: ["travelport_api.png"],
        approxStartDate: "16/10/2024",
        approxEndDate: "26/11/2024",
        techAndPackages: ['html','css','javascript','axios','node','express','hbs','joi','moment-timezone','xml-formatter','xmldom','xpath','dotenv'],
        sourceCode: "https://github.com/manish202/travelport_v1",
        livePreview: null,
        isHighlighted: false,
        isPrivateRepo: true,
    },
];

export default projects;